#!/usr/bin/env python3
# Copyright (C) 2026 Sten Tijhuis
# SPDX-License-Identifier: MIT
"""
Write the reference of the setup script: for every item, the exact commands that ticking it runs and that unticking
it runs to put things back, with a diff for every file they edit and a link to the code behind them.

    .github/scripts/generate-setup-reference.py          # rewrite the pages
    .github/scripts/generate-setup-reference.py --check  # fail when they no longer match the script

What the items run is not written down here. The script is imported and every item's own builders are run, the same
functions the window runs, on a machine that is described instead of read: a fresh CachyOS install for turning things
on, and the same machine with everything set up for turning things off. So the pages cannot say anything the window
does not do, and a change to the script that is not reflected in them fails the quality checks.

The files the setup script edits are fed the files a fresh Arch install ships (see STOCK below), so the diffs on the
site are what happens on a stock machine. The window shows the diff against your own files before it applies one.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import importlib.util
import os
import re
import shutil
import sys
import tempfile
from contextlib import ExitStack
from dataclasses import dataclass, field
from pathlib import Path
from types import ModuleType, SimpleNamespace
from unittest import mock

sys.dont_write_bytecode = True

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "src" / "static" / "scripts" / "quicksetup.py"
DOCS = REPO_ROOT / "src" / "content" / "docs"
OUT_DIR = DOCS / "setup-script" / "reference"
GENERATED = "<!-- Generated by .github/scripts/generate-setup-reference.py from quicksetup.py. Do not edit. -->"
USER = "your-username"
LANGUAGES = ("en", "nl")

# The files the setup script edits, as a fresh Arch install ships them. Where each one comes from:
#   custom.conf  gdm's data/gdm.conf-custom.in (GNOME/gdm on gitlab.gnome.org)
#   sudo         the sudo.pam of Arch's sudo package
#   gdm-password gdm's data/pam-arch/gdm-password.pam, which Arch installs in /etc/pam.d (a backup file of the package)
#   polkit-1     polkit's data/polkit-1.in with every PAM_FILE_INCLUDE_* set to system-auth, installed in /usr/lib/pam.d
STOCK = {
    "etc/gdm/custom.conf": (
        "# GDM configuration storage\n\n[daemon]\n\n[security]\n\n[debug]\n"
        "# Uncomment the line below to turn on debugging\n#Enable=true\n"),
    "etc/pam.d/sudo": (
        "#%PAM-1.0\nauth\t\tinclude\t\tsystem-auth\naccount\t\tinclude\t\tsystem-auth\n"
        "session\t\tinclude\t\tsystem-auth\nsession\t\toptional\tpam_systemd.so class=none\n"),
    "etc/pam.d/gdm-password": (
        "#%PAM-1.0\n\nauth       include                     system-local-login\n"
        "auth       optional                    pam_gnome_keyring.so\n\n"
        "account    include                     system-local-login\n\n"
        "password   include                     system-local-login\n"
        "password   optional                    pam_gnome_keyring.so use_authtok\n\n"
        "session    include                     system-local-login\n"
        "session    optional                    pam_gnome_keyring.so auto_start\n"),
    "usr/lib/pam.d/polkit-1": (
        "#%PAM-1.0\n\nauth       include      system-auth\naccount    include      system-auth\n"
        "password   include      system-auth\nsession    include      system-auth\n"),
}

# What a visitor reads on the page, per language. The commands and their descriptions are not translated: they are
# what the window shows, and the window is in English.
TEXT = {
    "en": {
        "intro": "The exact commands behind the **{title}** section of the [setup script]({setup}): what ticking an "
                 "item runs, and what unticking it runs to put things back.",
        "callout": "This page is generated from [`quicksetup.py`]({source}), the script itself, so it cannot say "
                   "anything the window does not do. Do not edit it by hand: change the script and run "
                   "`.github/scripts/generate-setup-reference.py`. [How to read this page]({reference}).",
        "on": "Turning it on", "off": "Turning it off (the way back)",
        "guide": "Guide", "needs": "Needs", "conflicts": "Cannot be on together with", "only": "Only on",
        "source": "Source", "marked": "Marked", "entry": "the entry",
        "recommended": "Recommended", "advanced": "`Advanced`", "aur": "`AUR`",
        "also": "Ticking it also ticks what it needs.",
        "diff": "The edit, as a diff:",
        "reboot": "Needs a reboot", "relogin": "Needs logging out and back in",
        "by_hand_on": "By hand, to set it up", "by_hand_off": "By hand, to undo it",
        "after_on": "Left for you after ticking it", "after_off": "Left for you after unticking it",
        "guide_only": "This row is a guide and has no checkbox: the steps stay yours, because a mistake in them can "
                      "stop the machine from booting.",
        "asus": "an ASUS laptop", "g16": "the Zephyrus G16 (GA605WV)", "nvidia": "a machine with an NVIDIA GPU",
        "mt7925": "a machine with the MediaTek MT7925 Wi-Fi card", "gnome": "the GNOME desktop",
        "color_title": "Color mode", "color_summary": "The Native and sRGB switch in the Display section. It works "
                                                      "right away, without an apply step.",
        "color_note": "There is no checkbox to untick here: switching to the other mode is the way back.",
        "on_packages": "From the AUR unless a repository you use carries the package: then it is the `pacman` line.",
    },
    "nl": {
        "intro": "De exacte commando's achter de sectie **{title}** van het [setup-script]({setup}): wat aanvinken "
                 "van een onderdeel draait, en wat uitvinken draait om alles terug te zetten.",
        "callout": "Deze pagina is gegenereerd uit [`quicksetup.py`]({source}), het script zelf, dus er kan niets "
                   "op staan wat het venster niet doet. Pas hem niet met de hand aan: verander het script en draai "
                   "`.github/scripts/generate-setup-reference.py`. [Zo lees je deze pagina]({reference}).",
        "on": "Aanzetten", "off": "Uitzetten (het terugdraaien)",
        "guide": "Handleiding", "needs": "Vereist", "conflicts": "Kan niet tegelijk aan met", "only": "Alleen op",
        "source": "Bron", "marked": "Label", "entry": "de regel",
        "recommended": "Aanbevolen", "advanced": "`Advanced`", "aur": "`AUR`",
        "also": "Aanvinken vinkt ook aan wat het nodig heeft.",
        "diff": "De wijziging, als diff:",
        "reboot": "Herstart nodig", "relogin": "Opnieuw inloggen nodig",
        "by_hand_on": "Met de hand, om het in te richten", "by_hand_off": "Met de hand, om het terug te draaien",
        "after_on": "Voor jou over na het aanvinken", "after_off": "Voor jou over na het uitvinken",
        "guide_only": "Deze rij is een handleiding en heeft geen vinkje: de stappen blijven van jou, omdat een fout "
                      "erin de machine kan laten stoppen met opstarten.",
        "asus": "een ASUS-laptop", "g16": "de Zephyrus G16 (GA605WV)", "nvidia": "een machine met een NVIDIA-GPU",
        "mt7925": "een machine met de MediaTek MT7925 Wi-Fi-kaart", "gnome": "het GNOME-bureaublad",
        "color_title": "Kleurstand", "color_summary": "De schakelaar tussen Native en sRGB in de sectie Display. Hij "
                                                      "werkt meteen, zonder toepassen.",
        "color_note": "Hier is geen vinkje om weg te halen: overschakelen naar de andere stand is de weg terug.",
        "on_packages": "Uit de AUR, tenzij een repository die je gebruikt het pakket heeft: dan is het de "
                       "`pacman`-regel.",
    },
}


def load_setup(home: Path):
    """Import the setup script with a home folder that is not yours, so the paths it works out never differ."""
    os.environ["HOME"] = str(home)
    for name in ("XDG_CACHE_HOME", "XDG_STATE_HOME", "XDG_CONFIG_HOME", "XDG_DATA_HOME"):
        os.environ.pop(name, None)
    spec = importlib.util.spec_from_file_location("quicksetup", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    sys.modules["quicksetup"] = module
    spec.loader.exec_module(module)
    return module


class Machine:
    """
    A machine that is described, not read: a CachyOS install on a Zephyrus G16 under GNOME. What is installed and set
    is given: nothing for a fresh machine, and everything the setup script can do for the one that turning things off
    starts from.
    """

    def __init__(self, q, home: Path, packages: set[str], aur: set[str], flatpaks: set[str],
                 settings: dict[tuple[str, str], str]) -> None:
        self.q = q
        self.os_name, self.is_arch, self.is_ostree = "CachyOS Linux", True, False
        self.user, self.home = USER, home
        self.vendor, self.board, self.bios = "ASUSTeK COMPUTER INC.", "GA605WV", "GA605WV.309"
        self.product = "ROG Zephyrus G16"
        self.desktop, self.session_type, self.is_gnome = "GNOME", "wayland", True
        self.is_asus, self.is_g16, self.model = True, True, "GA605WV"
        self.has_nvidia, self.has_mt7925 = True, True
        self.cmdline = ""
        self._packages, self._aur, self._flatpaks, self._settings = packages, aur, flatpaks, settings

    def pacman_installed(self) -> set[str]:
        return self._packages

    def in_repos(self, name: str) -> bool:
        return name not in self._aur

    def flatpaks(self) -> set[str]:
        return self._flatpaks

    def has_flathub(self) -> bool:
        return True

    def has_cmd(self, name: str) -> bool:
        return True

    def bootloader(self) -> str:
        return "limine"

    def unit_state(self, unit: str) -> str:
        return "enabled"

    def unit_active(self, unit: str) -> bool:
        return True

    def gsettings(self, schema: str, key: str) -> str | None:
        return self._settings.get((schema, key))

    def out(self, cmd: list[str]) -> str:
        return ""

    def kernel_package(self) -> str:
        return "linux-cachyos"

    def shell_version(self) -> tuple[int, str]:
        return 51, "51.0"

    def in_group(self, group: str) -> bool:
        return False

    def refresh(self) -> None:
        pass


LOADERS = ("limine", "grub", "systemd-boot")


@dataclass
class Recipe:
    """What one item runs, one way and the other, and the steps it leaves to you (by boot loader, as they differ)."""
    on: object | None = None            # a quicksetup.Plan; None for a row that is only a guide
    off: object | None = None
    manual_on: dict[str, list[str]] = field(default_factory=dict)
    manual_off: dict[str, list[str]] = field(default_factory=dict)


@dataclass
class Reference:
    """Everything the pages are written from."""
    q: ModuleType
    items: list
    recipes: dict[str, Recipe]
    sources: dict[str, list[tuple[str, int, int]]]
    swaps: list[tuple[str, str]]

    def section(self, item_id: str) -> str:
        return next(item.section for item in self.items if item.id == item_id)

    def title(self, item_id: str) -> str:
        return next(item.title for item in self.items if item.id == item_id)


def tidy(text: str, swaps: list[tuple[str, str]]) -> str:
    """Put the paths of the stand-in machine back as the paths of a real one."""
    for needle, replacement in sorted(swaps, key=lambda pair: -len(pair[0])):
        text = text.replace(needle, replacement)
    return text


def write_files(root: Path, files: dict[str, str]) -> None:
    for name, content in files.items():
        target = root / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")


def plan_of(builder, item, way: str, machine: Machine):
    """What one builder of one item puts in a plan. A builder that cannot be run says which one and why."""
    plan = machine.q.Plan()
    try:
        builder(machine, plan)
    except Exception as exc:  # whatever it is, the person fixing it needs to know which item it was
        sys.exit(f"{item.id}: turning it {way} fails on the stand-in machine: {type(exc).__name__}: {exc}")
    return plan


def build_recipes(q, workdir: Path) -> tuple[list, dict[str, Recipe], list[tuple[str, str]]]:
    """Run every builder of every item on the two stand-in machines. Returns the items, recipes and path swaps."""
    home = Path(os.environ["HOME"])
    swaps = [(str(home), f"/home/{USER}")]
    items = q.build_items(q.ExtensionCatalog())
    aur = {name for item in items for name in item.aur}
    recipes = {item.id: Recipe() for item in items}
    panel = q.Panel("eDP-1", "1002", q.Edid("SHP", "104D", "158E", "", None, None))
    gpg = {"user.signingkey": "<your key id>"}

    def environment(root: Path, git: dict[str, str], copies: list[Path]) -> ExitStack:
        """Point the script's own constants and probes at a stand-in root, for the duration of one pass."""
        swaps.append((str(root), ""))
        stack = ExitStack()
        for name, where in (("GDM_CONF", "etc/gdm/custom.conf"), ("PAM_DIR", "etc/pam.d"),
                            ("PAM_VENDOR_DIR", "usr/lib/pam.d")):
            stack.enter_context(mock.patch.object(q, name, root / where))
        stack.enter_context(mock.patch.object(q, "internal_panel", lambda: panel))
        stack.enter_context(mock.patch.object(q, "git_config", lambda key: git.get(key, "")))
        stack.enter_context(mock.patch.object(
            q, "system_color_copies", lambda s, retired_only=False: [] if retired_only else copies))
        stack.enter_context(mock.patch.object(q.shutil, "disk_usage",
                                              lambda path: SimpleNamespace(total=10**12, used=0, free=10**12)))
        return stack

    # A fresh machine: nothing installed, nothing set, the stock files where the packages put them.
    fresh_root = workdir / "fresh"
    write_files(fresh_root, STOCK)
    fresh = Machine(q, home, set(), aur, set(), {})
    with environment(fresh_root, gpg, []):
        for item in items:
            if item.guide_only:
                continue
            recipes[item.id].on = plan_of(item.on, item, "on", fresh)

    # The same machine with all of that done. What was installed and set comes from what turning it on did.
    packages = {name for r in recipes.values() if r.on for name in (*r.on.pacman, *r.on.aur)}
    flatpaks = {name for r in recipes.values() if r.on for name in r.on.flatpak}
    settings = {}
    for recipe in recipes.values():
        for step in (recipe.on.steps if recipe.on else []):
            if step.argv and step.argv[:2] == ["gsettings", "set"]:
                settings[(step.argv[2], step.argv[3])] = step.argv[4]
    configured_root = workdir / "configured"
    wired = {name: q.pam_with_u2f(text) for name, text in
             ((n, STOCK[f"etc/pam.d/{n}"]) for n in ("sudo", "gdm-password"))}
    wired["polkit-1"] = q.pam_with_u2f(STOCK["usr/lib/pam.d/polkit-1"])
    files = {f"etc/pam.d/{name}": text for name, text in wired.items()}
    files["etc/gdm/custom.conf"] = q.set_ini_keys(STOCK["etc/gdm/custom.conf"], "daemon", {
        "AutomaticLoginEnable": "True", "AutomaticLogin": USER})
    files["etc/gdm/custom.conf.zephyrus-setup.bak"] = STOCK["etc/gdm/custom.conf"]
    files["usr/lib/pam.d/polkit-1"] = STOCK["usr/lib/pam.d/polkit-1"]
    write_files(configured_root, files)
    done = Machine(q, home, packages, aur, flatpaks, settings)
    profiles = [q.COLORD_STORE / name for _, name in q.profile_set(done, panel)]
    full_git = {"user.signingkey": "<your key id>", "commit.gpgsign": "true", "tag.gpgsign": "true"}
    with environment(configured_root, full_git, profiles):
        for item in items:
            if item.guide_only:
                continue
            recipes[item.id].off = plan_of(item.off, item, "off", done)

    # The steps left for you can depend on the boot loader, so they are worked out for each one.
    for item in items:
        for loader in LOADERS:
            machine = Machine(q, home, set(), aur, set(), {})
            machine.bootloader = lambda loader=loader: loader
            recipes[item.id].manual_on[loader] = item.manual_steps(machine)
            recipes[item.id].manual_off[loader] = item.manual_off_steps(machine)
    return items, recipes, swaps


def source_map(q) -> dict[str, list[tuple[str, int, int]]]:
    """
    Where the code behind every item is: its entry in build_items() and the named functions that entry hands over
    (as (label, first line, last line)). Read from the syntax tree, so it is the file as committed.
    """
    tree = ast.parse(SCRIPT.read_text(encoding="utf-8"))
    functions = {node.name: (node.lineno, node.end_lineno) for node in tree.body if isinstance(node, ast.FunctionDef)}
    build = next(node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name == "build_items")
    positional = {"Item": (6, 7), "package_item": ()}
    keywords = ("extra_on", "extra_off", "on_blocker", "off_blocker")
    found: dict[str, list[tuple[str, int, int]]] = {}
    for node in ast.walk(build):
        if not (isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id in positional
                and node.args and isinstance(node.args[0], ast.Constant) and isinstance(node.args[0].value, str)):
            continue
        refs = [node.args[i] for i in positional[node.func.id] if i < len(node.args)]
        refs += [kw.value for kw in node.keywords if kw.arg in keywords]
        entry = [("entry", node.lineno, node.end_lineno)]
        for ref in refs:
            if isinstance(ref, ast.Name) and ref.id in functions:
                entry.append((ref.id, *functions[ref.id]))
        found[node.args[0].value] = entry
    # The extensions are made in a loop from the EXTENSIONS table, one entry each.
    for node in ast.walk(tree):
        if (isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id == "ExtensionSpec"
                and node.args and isinstance(node.args[0], ast.Constant)):
            found[f"ext-{node.args[0].value}"] = [("entry", node.lineno, node.end_lineno)] + [
                (name, *functions[name]) for name in ("extension_item", "install_extension", "remove_extension")]
    return found


def guide_title(page: str, lang: str) -> str:
    """The title of a guide page, read from its front matter, in the language of the page that links to it."""
    base = DOCS / page.strip("/")
    suffixes = (".nl.md", ".md") if lang == "nl" else (".md",)
    candidates = [base.with_name(base.name + suffix) for suffix in suffixes]
    candidates += [base / "_index.nl.md", base / "_index.md"] if lang == "nl" else [base / "_index.md"]
    for path in candidates:
        if path.is_file():
            match = re.search(r'^title:\s*"?(.*?)"?\s*$', path.read_text(encoding="utf-8"), re.MULTILINE)
            if match and match.group(1):
                return match.group(1)
    return page.strip("/") or "Guides"


def fence(language: str, text: str) -> str:
    return f"```{language}\n{text.rstrip()}\n```"


def commands_text(q, commands: list, swaps: list[tuple[str, str]]) -> str:
    """The commands of a direction as one block of shell: the same lines the window lists, with comments as headings."""
    lines: list[str] = []
    for phase, title in q.PHASE_TITLES.items():
        group = [command for command in commands if command.phase == phase]
        if not group:
            continue
        lines += [f"# {'-' * 3} {title} {'-' * 3}", ""]
        for command in group:
            lines.append(f"# {command.desc}")
            lines += command.text.splitlines()
            lines.append("")
    return tidy("\n".join(lines).rstrip(), swaps)


def direction(q, plan, swaps: list[tuple[str, str]], text: dict[str, str]) -> list[str]:
    """The Markdown for one direction of one item: its commands, the diffs, and what the person should know."""
    commands = q.plan_commands(plan)
    out = [fence("bash", commands_text(q, commands, swaps)), ""]
    diffs = [command.diff for command in commands if command.diff]
    if diffs:
        out += [text["diff"], ""]
        for diff in diffs:
            out += [fence("diff", tidy(diff, swaps)), ""]
    facts = [tidy(note, swaps) for note in plan.notes]
    if plan.reboot_for:
        facts.append(f"{text['reboot']}: {', '.join(plan.reboot_for)}.")
    if plan.relogin_for:
        facts.append(f"{text['relogin']}: {', '.join(plan.relogin_for)}.")
    out += [f"- {fact}" for fact in facts]
    return out + [""] if facts else out


def steps_block(label: str, steps: list[str]) -> list[str]:
    return [f"**{label}**", "", *[f"{n}. {step}" for n, step in enumerate(steps, 1)], ""]


def manual_blocks(label: str, by_loader: dict[str, list[str]]) -> list[str]:
    """Steps by hand. When the boot loader changes them, each boot loader gets its own list."""
    lists = {loader: steps for loader, steps in by_loader.items() if steps}
    if not lists:
        return []
    if len({tuple(steps) for steps in lists.values()}) == 1:
        return steps_block(label, next(iter(lists.values())))
    out = []
    for loader, steps in lists.items():
        out += steps_block(f"{label} ({loader})", steps)
    return out


def item_markdown(ref: Reference, item, lang: str) -> list[str]:
    """One item: what it is, where it comes from, and the commands for turning it on and off."""
    q, text, recipe = ref.q, TEXT[lang], ref.recipes[item.id]
    repo = f"https://github.com/{q.REPO}/blob/main/src/static/scripts/quicksetup.py"
    out = [f"### {item.title} {{#{item.id}}}", "", item.summary, ""]

    def link(other: str) -> str:
        where = "" if ref.section(other) == item.section else f"../{ref.section(other)}/"
        return f"[{ref.title(other)}]({where}#{other})"

    # The anchors are those of the English guides. The Dutch guides have translated headings, so a Dutch page links
    # to the guide itself: an anchor that is not there is a link that does not work.
    page, _, anchor = item.doc.partition("#")
    guide = f'{{{{< relref "/docs/{page.strip("/")}" >}}}}' + (f"#{anchor}" if anchor and lang == "en" else "")
    facts = [f"**{text['guide']}:** [{guide_title(page, lang)}]({guide})"]
    if item.requires:
        facts.append(f"**{text['needs']}:** " + ", ".join(link(other) for other in item.requires))
    if item.conflicts:
        facts.append(f"**{text['conflicts']}:** " + ", ".join(link(other) for other in item.conflicts))
    only = ([text[item.hardware]] if item.hardware else []) + ([text["gnome"]] if item.needs_gnome else [])
    if only:
        facts.append(f"**{text['only']}:** " + ", ".join(only))
    marks = ([text["recommended"]] if item.recommended and not item.advanced else []) \
        + ([text["advanced"]] if item.advanced else []) + ([text["aur"]] if item.aur else [])
    if marks:
        facts.append(f"**{text['marked']}:** " + ", ".join(marks))
    code = [f"[{text['entry']}]({repo}#L{start}-L{end})" if label == "entry" else f"[`{label}`]({repo}#L{start}-L{end})"
            for label, start, end in ref.sources[item.id]]
    facts.append(f"**{text['source']}:** " + " · ".join(code))
    out += [f"- {fact}" for fact in facts] + [""]
    if item.guide_only:
        out += [text["guide_only"], ""]
        out += manual_blocks(text["by_hand_on"], recipe.manual_on)
        out += manual_blocks(text["by_hand_off"], recipe.manual_off)
        return out
    if item.requires:
        out += [text["also"], ""]
    out += [f"**{text['on']}**", ""] + direction(q, recipe.on, ref.swaps, text)
    if item.aur:
        out += [text["on_packages"], ""]
    out += manual_blocks(text["after_on"], recipe.manual_on)
    out += [f"**{text['off']}**", ""] + direction(q, recipe.off, ref.swaps, text)
    return out + manual_blocks(text["after_off"], recipe.manual_off)


def section_page(ref: Reference, key: str, title: str, weight: int, lang: str) -> str:
    q, text = ref.q, TEXT[lang]
    source = f"https://github.com/{q.REPO}/blob/main/src/static/scripts/quicksetup.py"
    body = [GENERATED, "", text["intro"].format(title=title, setup='{{< relref "/docs/setup-script" >}}'), "",
            '{{< callout type="info" >}}',
            text["callout"].format(source=source, reference='{{< relref "/docs/setup-script/reference" >}}'),
            "{{< /callout >}}", ""]
    if key == "display":
        body += [f"## {text['color_title']} {{#color-mode}}", "", text["color_summary"], "",
                 fence("text", q.color_runs("eDP-1")), "", text["color_note"], ""]
    groups: dict[str, list] = {}
    for item in (item for item in ref.items if item.section == key):
        groups.setdefault(item.group or title, []).append(item)
    for group, members in groups.items():
        body += [f"## {group}", ""]
        for item in members:
            body += item_markdown(ref, item, lang)
    edit = f"https://github.com/{q.REPO}/edit/main/src/static/scripts/quicksetup.py"
    header = ["---", f'title: "{title}"', f"weight: {weight}", f"editURL: {edit}", "---", "",
              "<!-- markdownlint-disable MD010 -->", ""]
    return "\n".join(header + body).rstrip() + "\n"


def render_all() -> dict[Path, str]:
    """Every page the reference consists of, as {path: text}."""
    workdir = Path(tempfile.mkdtemp(prefix="zs-"))
    try:
        home = workdir / "home" / USER
        home.mkdir(parents=True)
        q = load_setup(home)
        items, recipes, swaps = build_recipes(q, workdir)
        ref = Reference(q, items, recipes, source_map(q), swaps)
        problems = [f"{item.id}: it has no way back (no off)" for item in items
                    if not item.guide_only and (item.on is None or item.off is None)]
        problems += [f"{item.id}: turning it {way} runs nothing" for item in items if not item.guide_only
                     for way, plan in (("on", recipes[item.id].on), ("off", recipes[item.id].off)) if plan.empty]
        problems += [f"{item.id}: no entry found in build_items()" for item in items if item.id not in ref.sources]
        if problems:
            sys.exit("The reference cannot be written:\n  " + "\n  ".join(problems))
        pages: dict[Path, str] = {}
        for weight, (key, title, _icon, _about) in enumerate(q.SECTIONS, start=1):
            for lang in LANGUAGES:
                name = f"{key}.md" if lang == "en" else f"{key}.nl.md"
                pages[OUT_DIR / name] = section_page(ref, key, title, weight, lang)
        return pages
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Write the reference of the setup script from the script itself.")
    parser.add_argument("--check", action="store_true", help="fail when the pages on disk are not what the script says")
    args = parser.parse_args()
    pages = render_all()
    stale = []
    for path, text in pages.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        if current == text:
            continue
        stale.append(path)
        if args.check:
            diff = difflib.unified_diff(current.splitlines(), text.splitlines(), f"{path.name} (committed)",
                                        f"{path.name} (from the script)", lineterm="", n=1)
            print("\n".join(list(diff)[:40]), file=sys.stderr)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO_ROOT)}")
    leftovers = [path for path in OUT_DIR.glob("*.md") if path not in pages and not path.name.startswith("_index")]
    for path in leftovers:
        stale.append(path)
        if args.check:
            print(f"{path.relative_to(REPO_ROOT)} belongs to a section that no longer exists", file=sys.stderr)
        else:
            path.unlink()
            print(f"removed {path.relative_to(REPO_ROOT)}")
    if args.check and stale:
        sys.exit(f"\n{len(stale)} page(s) of the setup reference are out of date. Rewrite them with:\n"
                 "  .github/scripts/generate-setup-reference.py")
    if not stale:
        print(f"The setup reference is current ({len(pages)} pages).")


if __name__ == "__main__":
    main()
